Green/Green/Controllers/ContactController.cs
using Green.Models.Entity;
using Green.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Green.Controllers
{
    public class ContactController : Controller
    {
        private Entity db = new Entity();
        // GET: Contact
        public ActionResult Index(string Name, string Email, string Text, string Newsletter)
        {
            VmContact wm = new VmContact();
            wm.Contacts = db.Contacts.ToList();
            wm.ContactSliders = db.ContactSliders.ToList();
            wm.ContactTexts = db.ContactTexts.ToList();
            wm.NewsLetters = db.NewsLetters.ToList();

            return View(wm);
        }
    }
}

Green/Green/Controllers/NewsController.cs
using Green.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Green.Controllers
{
    public class NewsController : Controller
    {
        private Entity db = new Entity();
        // GET: News
        public ActionResult Index()
        {
            return View();
        }
    }
}

Green/Green/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("CO2 Beregner", "Index", "Carbon")</li>*@
                    <li>@Html.ActionLink("Nyheder", "Index", "News")</li>
                    <li>@Html.ActionLink("Blog", "Index", "Blog")</li>
                    <li>@Html.ActionLink("Om os", "Index", "Contact")</li>
                    <li>@Html.ActionLink("Min side", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>
<div class="container-fluid">
    <div class="global-footer">
        <div class="ads-wrapper">
            sdf
        </div>
    </div>
</div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>